name: App build

on:
  push:
    branches:
      - "update-value-multiple-cells"

defaults:
  run:
    # -l: use login shell (required when using Conda)
    shell: bash -l {0}

env:
  PYTEST_ADDOPTS: --color=yes

jobs:
  windows-build:
    name: Windows Build

    runs-on: windows-latest

    # env:
    #   CSC_LINK: ${{ secrets.CSC_LINK }}
    #   CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}

    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          activate-environment: pareto-ui-env
      
      - name: Install Azure Signtool
        run: |
          dotnet tool install --global AzureSignTool

      - name: Install Electron JS dependencies
        run: |
          npm --prefix electron clean-install
      - name: Install frontend JS dependencies
        run: |
          npm --prefix electron/ui clean-install
      - name: Get idaes extensions
        run: idaes get-extensions

      # - name: Install Pareto locally
      #   working-directory: ../
      #   run: git clone https://github.com/MichaelPesce/project-pareto.git && cd project-pareto && pip install --progress-bar off .

      - name: Install Pareto locally
        working-directory: ../
        run: git clone https://github.com/project-pareto/project-pareto.git && cd project-pareto && git fetch --all --tags && git checkout 0.9.0rc1 && pip install --progress-bar off .

      - name: Install numpy 1.24.3
        run: |
          pip uninstall -y numpy && pip install numpy==1.24.3

      - name: Build Backend
        run: npm --prefix electron run build-backend

      - name: Build Frontend
        run: npm --prefix electron run build-frontend-win

      - name: Build Windows Distribution
        run: npm --prefix electron run electron-build-win

      - name: Display file names
        run: cd electron && cd dist && ls

      - name: Sign Windows Distribution
        run: |
          AzureSignTool sign -kvu "${{ secrets.AZURE_KEY_VAULT_URI }}" -kvi "${{ secrets.AZURE_CLIENT_ID }}" -kvt "${{ secrets.AZURE_TENANT_ID }}" -kvs "${{ secrets.AZURE_CLIENT_SECRET }}" -kvc ${{ secrets.AZURE_CERT_NAME }} -tr http://timestamp.digicert.com -v electron/dist/ParetoUI-23.11.02-win64.exe

      - name: Upload artifact for windows build
        uses: actions/upload-artifact@v3
        if: always()
        with:
            name: windows-pareto-dist
            path: |
              electron/dist/ParetoUI-23.11.02-win64.exe
  # windows-build:
  #   name: Windows Build

  #   runs-on: windows-latest

  #   env:
  #     CSC_LINK: ${{ secrets.CSC_LINK }}
  #     CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}

  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: conda-incubator/setup-miniconda@v2
  #       with:
  #         environment-file: environment.yml
  #         activate-environment: pareto-ui-env

  #     - name: Install Electron JS dependencies
  #       run: |
  #         npm --prefix electron clean-install
  #     - name: Install frontend JS dependencies
  #       run: |
  #         npm --prefix electron/ui clean-install
  #     - name: Get idaes extensions
  #       run: idaes get-extensions

  #     # - name: Install Pareto locally
  #     #   working-directory: ../
  #     #   run: git clone https://github.com/MichaelPesce/project-pareto.git && cd project-pareto && git fetch --all && git checkout 0.5.0_release && pip install --progress-bar off .

  #     - name: Install Pareto locally
  #       working-directory: ../
  #       run: git clone https://github.com/project-pareto/project-pareto.git && cd project-pareto && git fetch --all --tags && git checkout 0.8.0 && pip install --progress-bar off .

  #     - name: Build Backend
  #       run: npm --prefix electron run build-backend

  #     - name: Build Frontend
  #       run: npm --prefix electron run build-frontend-win

  #     - name: Build Windows Distribution
  #       run: npm --prefix electron run electron-build-win

  #     - name: Upload artifact for windows build
  #       uses: actions/upload-artifact@v3
  #       if: always()
  #       with:
  #           name: windows-pareto-dist
  #           path: |
  #             electron/dist/ParetoUI-23.11.02-win64.exe